from abc import ABC, abstractmethod
from typing import Optional

from app.domain.entities.user import User


class IUserRepository(ABC):
    @abstractmethod
    def create(self, user: User) -> User: ...

    @abstractmethod
    def get_by_email(self, email: str) -> Optional[User]: ...

    @abstractmethod
    def get_by_id(self, id: int) -> Optional[User]: ...

    @abstractmethod
    def delete(self, id: int) -> bool: ...

    def get_roles(self, user_id: int) -> set[str]: ...
    def get_permissions(self, user_id: int) -> set[str]: ...
    def set_roles(self, user_id: int, role_names: list[str]) -> set[str]: ...
